language: scala

scala:
  - 2.11.12
  - 2.12.10
  - 2.13.1

jdk:
  - oraclejdk9

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier